- hosts: localhost
  gather_facts: no 
  vars_files:
    - custom_vars/filesystems_creation_specific_vars.yml
  vars_prompt:
    - name: "vgname"
      prompt: "Default vg is datavg.Enter your desired VolumeGroup name if you want to change default volume group name: "
      default: datavg

  tasks:
    - name: dispaly
      debug:
        #msg: "{{ item.name }} has value ---> {{ item.size }}"
        #msg: "{{ item.name }} "
        msg: "/dev/mapper/{{ vgname }}/{{ item.name }}"
      with_items: "{{ lvm_list }}"
