- hosts: all
  gather_facts: yes
  become: yes
  vars:
    current_patch: '11-08-2019'

  tasks:
    - name: Broadcast message to all logged in users reminding of patching
      script: scripts/wall.sh
      #when: ansible_local['patch']['patch_ver'] != "{{ current_patch }}"
      when: ansible_local['patch']['patch_ver'] not eq 'current_patch'

