---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: copy bashrc config for user db2inst1
      copy:
        src: files/bashrc.conf
        dest: /db2home/db2inst1/.bashrc
        owner: db2inst1
        group: db2iadm1
        mode: '0644'

    - name: copy ulimits for user db2inst1
      copy:
        src: files/db2inst1_ulimits.conf
        dest: /etc/security/limits.d/db2inst1.conf
        owner: root
        group: root
        mode: '0644'

    - name: copy sysctl for kernel swapinesss db2
      copy:
        src: files/sysctl_db2.conf
        dest: /etc/sysctl.d/db2.conf
        owner: root
        group: root
        mode: '0644'

    - name: copy sysctl for kernel swapinesss db2
      copy:
        src: files/bash_p.conf
        dest: /db2home/db2inst1/.bash_profile
        owner: db2inst1
        group: db2iadm1
        mode: '0644'

    - name: install required pkgs
      yum:
        name: "{{ item }}"
        state: present
      with_items:
          - pam.i686
          - pam.x86_64
          - pam-devel.i686
          - pam-devel.x86_64
          - libstdc++.i686
          - libstdc++.x86_64
                



