- hosts: all
  gather_facts: no
  become: yes
  vars_files:
    - '../../custom_vars/filesystems_creation_specific_vars.yml'
  #vars_prompt:
    #- name: "vgname"
     # prompt: "Default vg is datavg.Enter your desired VolumeGroup name if you want to change default volume group name: "
     # default: datavg
    
  tasks:
    #- name: create home directory
      #file:
        #path: /db2home/db2inst1
        #state: directory
        #owner: db2inst1
       # group: db2iadm1
        #mode: '0700'

    - name: create db2iadm1  group locally
      group:
        name: db2iadm1
        gid: 3010
        state: present

    - name: create db2inst1 user locally
      user:
        name: db2inst1
        group: db2iadm1
        groups: sysadmins
        comment: db2inst1 user
        shell: /bin/bash
        home: /db2home/db2inst1
        uid: 3009
        password: $6$jGLTiZuqwBtbHVFJ$DXcWI94m2aTSNjMzGqvDJQHIfdhWkADA4bskX6tNLVMrzJQe5eAc9YogU2cyD6uaKhXgQSyLjqjOHlvx9msGs0

    - name: create db2fadm1  group locally
      group:
        name: db2fadm1
        gid: 3011
        state: present

    - name: create db2fenc1 user locally
      user:
        name: db2fenc1
        group: db2fadm1
        #groups: sysadmins
        comment: db2fenc1 user
        shell: /bin/bash
        home: /db2home/db2fenc1
        uid: 3010
        password: $6$RpkmBhrKyj6i182O$pXDMTLGlW/T1rFb3AVEClaZPbKX6WgsG9G9TqaOKYCsu9mSmzs2B1ND7RWtCwEDFaiKDFgysbTRze6YdB/1Wj0



    - name: create required mountpoints
      file:
        path: "{{ item.mountpoint_name }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
        recurse: yes
      with_items: "{{ lvm_list }}"
 
    - name: create physical volume and volume group
      lvg:
        vg: datavg
        pvs: /dev/sdc,/dev/sdd,/dev/sde,/dev/sdf,/dev/sdg

    #- name: create physical volume and volume group
      #lvg:
        #vg: datavg
        #pvs: /dev/sdd,/dev/sde,/dev/sdf,/dev/sdg

#    - name: extend volume group
  #    script: scripts/vgextend.sh

    - name: create required lvms
      lvol:
        vg: datavg
        lv: "{{ item.name }}"
        state: present
   #     state: absent
        #force: yes
        size: "{{ item.size }}"
      with_items: "{{ lvm_list }}"

    - name: create required xfs type filesystems format on create lvm's
      filesystem:
        fstype: xfs
        dev: "/dev/mapper/datavg-{{ item.name }}"
      with_items: "{{ lvm_list }}" 

    - name: include mounts in fstab
      mount:
        path: "{{ item.mountpoint_name }}"
        src: "/dev/mapper/datavg-{{ item.name }}"
        fstype: xfs
        opts: defaults
        passno: '2'
        state: mounted
      with_items: "{{ lvm_list }}"

    - name: change to  required permissions
      file:
        path: "{{ item }}"
        owner: db2inst1
        group: db2iadm1
        mode: '0755'
        recurse: yes
      with_items:
        - /db2home
        - /dba_work
        - /dbfs/dbtt1cu1

    - name: change webshpere required permissions
      file:
        path: /opt/IBM/WebSphere
        owner: wasadm
        group: wasadm
        mode: '0755'
        recurse: yes

      
    
 
