---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: change webshpere required permissions
      file:
        path: /opt/IBM/WebSphere
        owner: wasadm
        group: wasadm
        mode: '0755'
        recurse: yes

