- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: run script on local host
      shell: /home/prav/ansible_stuff/playbooks/linux_internal_os_specific/linux_stuff/scripts/windows_specific_combine_csv_add_headers.sh
