- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: run script on local host
      shell: ../scripts/combine_csv_add_headers.sh

    - name: import combined csv to itop
      shell:
        cmd: 'php /var/www/html/itop/webservices/import.php --auth_user=chintu --auth_pwd=chintu --csvfile=/home/prav/combined_csv_records/combined \
              --charset="UTF-8" --class="Server" --reconcialiationkeys="name,organization->name,description,ram,cpu,os family->name,os version->name" | tr -d '#''
      register: import_job_status

    - name: display import output
      debug:
         #msg: "Issues reported are ---> {{ item.#Issues }}"
         #msg:  "{{ item.#Issues }}"
         msg: "Issues reported are ---> {{ item.Issues }}"
      with_items: "{{ import_job_status.stdout_lines }}"
      #with_items: "{{ import_job_status }}"
      
    
