- hosts: all
  gather_facts: no
  become: yes
  vars_files:
    - '../custom_vars/filesystems_creation_specific_vars.yml'
  vars_prompt:
    - name: "vgname"
      prompt: "Default vg is datavg.Enter your desired VolumeGroup name if you want to change default volume group name: "
      default: datavg
    
  tasks:

    - name: create required mountpoints
      file:
        path: "{{ item.mountpoint_name }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
        recurse: yes
      with_items: "{{ lvm_list }}"
 
    - name: create physical volume and volume group
      lvg:
        vg: "{{ vgname }}"
        pvs: "{{ item }}"
      with_items: "{{ input_disks }}"

    - name: create required lvms
      lvol:
        vg: "{{ vgname }}"
        lv: "{{ item.name }}"
        size: "{{ item.size }}"
      with_items: "{{ lvm_list }}"

    - name: create required xfs type filesystems format on create lvm's
      filesystem:
        fstyp: xfs
        dev: "/dev/mapper/{{ vgname }}-{{ item.name }}"
      with_items: "{{ lvm_list }}" 

    - name: include mounts in fstab
      mount:
        path: "{{ item.mountpoint_name }}"
        src: "/dev/mapper/{{ vgname }}/{{ item.name }}"
        fstype: xfs
        opts: defaults
        state: mounted
      with_items: "{{ lvm_list }}"
      
    
 
